language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
sudo: required
dist: trusty

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; sudo apt-get install -qq git-core libcppunit-dev graphviz valgrind g++-4.8; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm cppunit graphviz valgrind && brew link --force llvm; fi
before_script:
  - ./bootstrap
script:
  - make
  - make check
  - tests/checkbinary.sh
  - tests/checkTotalProb.sh
